// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1( lv_event_t * e);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Image1;
void ui_event_Panel6( lv_event_t * e);
extern lv_obj_t *ui_Panel6;
void ui_event_Panel3( lv_event_t * e);
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_Image5;
void ui_event_Panel7( lv_event_t * e);
extern lv_obj_t *ui_Panel7;
void ui_event_Panel9( lv_event_t * e);
extern lv_obj_t *ui_Panel9;
void ui_event_Panel8( lv_event_t * e);
extern lv_obj_t *ui_Panel8;
extern lv_obj_t *ui_Label3;
void ui_event_Label4( lv_event_t * e);
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label5;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t *ui_Screen3;
extern lv_obj_t *ui_Image6;
extern lv_obj_t *ui_Image8;
extern lv_obj_t *ui_Image10;
extern lv_obj_t *ui_Label28;
extern lv_obj_t *ui_Arc3;
extern lv_obj_t *ui_Arc4;
void ui_event_Panel2( lv_event_t * e);
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Label29;
extern lv_obj_t *ui_Label30;
void ui_event_Label31( lv_event_t * e);
extern lv_obj_t *ui_Label31;
extern lv_obj_t *ui_Label32;
extern lv_obj_t *ui_Label33;
extern lv_obj_t *ui_Label34;
extern lv_obj_t *ui_Label35;
extern lv_obj_t *ui_Label36;
extern lv_obj_t *ui_Label37;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t *ui_Screen5;
extern lv_obj_t *ui_Image7;
void ui_event_Panel1( lv_event_t * e);
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_Label18;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t *ui_Screen4;
extern lv_obj_t *ui_Image9;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Arc1;
extern lv_obj_t *ui_Arc2;
void ui_event_Panel4( lv_event_t * e);
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label8;
void ui_event_Label9( lv_event_t * e);
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_1658053739);   // assets\AWD Rice Monitoring (23).png
LV_IMG_DECLARE( ui_img_270506670);   // assets\AWD Rice Monitoring (24).png
LV_IMG_DECLARE( ui_img_537354039);   // assets\AWD Rice Monitoring (25).png
LV_IMG_DECLARE( ui_img_1658026312);   // assets\AWD Rice Monitoring (13).png
LV_IMG_DECLARE( ui_img_537381466);   // assets\AWD Rice Monitoring (15).png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
